// Generated by CoffeeScript 1.7.1
(function() {
  define(function() {
    return {
      createAudio: function() {
        var a;
        a = new Audio();
        a.controls = true;
        a.canPlayType("audio/mpeg");
        a.src = "music/mario.mp3";
        document.querySelector("#media").appendChild(a);
        return a.play();
      }
    };
  });

}).call(this);

//# sourceMappingURL=audio.map
