// Generated by CoffeeScript 1.7.1
(function() {
  var Game;

  Game = (function() {
    var size;

    size = {
      x: 1200,
      y: 600
    };

    function Game() {
      this.ctx = document.getElementById('game').getContext('2d');
    }

    Game.prototype.draw = function() {
      this.ctx.fillStyle = "rgb(220, 220, 220)";
      return this.ctx.fillRect(0, 0, size.x, size.y);
    };

    window.Game = Game;

    return Game;

  })();

}).call(this);

//# sourceMappingURL=game.map
