// Generated by CoffeeScript 1.7.1
(function() {
  define([], function() {
    var Home;
    return Home = (function() {
      function Home(x, y) {
        this.x = x;
        this.y = y;
        this.name = "Home";
      }

      Home.prototype.draw = function(ctx, xx, yy) {
        var image;
        image = new Image();
        image.src = "img/house.png";
        return ctx.drawImage(image, xx, yy, 30, 30);
      };

      Home.prototype.shoot = function(enemies, owner) {
        var enemy, key, pos, _ref, _results;
        this.enemies = enemies;
        this.owner = owner;
        _ref = this.enemies;
        _results = [];
        for (key in _ref) {
          enemy = _ref[key];
          pos = enemy.position();
          if (pos.x >= 20) {
            pos.x -= 20;
            if (pos.x === this.x && pos.y === this.y) {
              this.enemies.splice(key, 1);
              _results.push(this.owner.lives--);
            } else {
              _results.push(void 0);
            }
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };

      return Home;

    })();
  });

}).call(this);

//# sourceMappingURL=home.map
