// Generated by CoffeeScript 1.7.1
(function() {
  requirejs.config({
    baseUrl: 'js'
  });

  requirejs(['game', 'player', 'home', 'towers/fire', 'towers/water', 'towers/nature', 'towers/wind'], function(game, player, home, fire, water, nature, wind) {
    var g;
    new Player;
    g = new Game;
    return g.clear();
  });

}).call(this);

//# sourceMappingURL=MTD.map
