// Generated by CoffeeScript 1.7.1
(function() {
  requirejs.config({
    baseUrl: 'js'
  });

  define(['game', 'player', 'home', 'towers/fire', 'towers/water', 'towers/nature', 'towers/wind', 'enemy'], function(Game, player, home, fire, water, nature, wind) {
    return new Game().clear();
  });

}).call(this);

//# sourceMappingURL=MTD.map
