// Generated by CoffeeScript 1.7.1
(function() {
  requirejs.config({
    baseUrl: 'js'
  });

  define(['game'], function(Game) {
    return new Game().clear();
  });

}).call(this);

//# sourceMappingURL=MTD.map
