// Generated by CoffeeScript 1.7.1
(function() {
  var Fire;

  Fire = (function() {
    function Fire() {
      this.name = "Fire";
    }

    Fire.prototype.draw = function(ctx, x, y) {
      var image;
      this.ctx = ctx;
      this.x = x;
      this.y = y;
      image = new Image();
      image.src = "img/fire.svg";
      return image.onload = (function(_this) {
        return function() {
          return _this.ctx.drawImage(image, _this.x, _this.y, 30, 30);
        };
      })(this);
    };

    return Fire;

  })();

  window.Fire = Fire;

}).call(this);

//# sourceMappingURL=fire.map
