// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['towers/tower'], function(Tower) {
    var Fire;
    return Fire = (function(_super) {
      __extends(Fire, _super);

      function Fire(x, y) {
        this.x = x;
        this.y = y;
        this.name = "Fire";
        this.img = "img/fire.svg";
        this.price = 30;
        this.attack = 2;
        this.range = 4;
        this.speed = 2000;
        this.lastShot = 0;
      }

      return Fire;

    })(Tower);
  });

}).call(this);

//# sourceMappingURL=fire.map
