// Generated by CoffeeScript 1.7.1
(function() {
  var Fire;

  Fire = (function() {
    function Fire() {
      this.name = "Fire";
      this.price = 30;
      this.attack = 2;
      this.range = 4;
      this.speed = 3;
    }

    Fire.prototype.draw = function(ctx, x, y) {
      var image;
      this.ctx = ctx;
      this.x = x;
      this.y = y;
      image = new Image();
      image.src = "img/fire.svg";
      return this.ctx.drawImage(image, this.x, this.y, 30, 30);
    };

    return Fire;

  })();

  window.Fire = Fire;

}).call(this);

//# sourceMappingURL=fire.map
