// Generated by CoffeeScript 1.7.1
(function() {
  var Nature;

  Nature = (function() {
    function Nature() {
      this.name = "Nature";
      this.price = 30;
      this.attack = 2;
      this.range = 4;
      this.speed = 3;
    }

    Nature.prototype.draw = function(ctx, x, y) {
      var image;
      this.ctx = ctx;
      this.x = x;
      this.y = y;
      image = new Image();
      image.src = "img/leaf.svg";
      return image.onload = (function(_this) {
        return function() {
          return _this.ctx.drawImage(image, _this.x, _this.y, 30, 30);
        };
      })(this);
    };

    return Nature;

  })();

  window.Nature = Nature;

}).call(this);

//# sourceMappingURL=nature.map
