// Generated by CoffeeScript 1.7.1
(function() {
  var Tower;

  Tower = (function() {
    var attack, speed;

    function Tower() {}

    attack = 5;

    speed = 2;

    return Tower;

  })();

}).call(this);

//# sourceMappingURL=tower.map
