// Generated by CoffeeScript 1.7.1
(function() {
  define([], function() {
    var Tower;
    return Tower = (function() {
      function Tower() {}

      Tower.prototype.construcor = function() {
        return this.lastShot;
      };

      Tower.prototype.draw = function(ctx, xx, yy) {
        var image;
        this.ctx = ctx;
        image = new Image();
        image.src = this.img;
        return this.ctx.drawImage(image, xx, yy, 30, 30);
      };

      Tower.prototype.shoot = function(enemies) {
        var enemy, pos, _i, _len, _ref, _results;
        this.enemies = enemies;
        _ref = this.enemies;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          enemy = _ref[_i];
          pos = enemy.position();
          if (pos.x >= this.x - this.range && pos.x <= this.x + this.range && pos.y >= this.y - this.range && pos.y <= this.y + this.range) {
            _results.push(console.log(enemy));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };

      return Tower;

    })();
  });

}).call(this);

//# sourceMappingURL=tower.map
