// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['towers/tower', 'towers/config'], function(Tower, config) {
    var Wind;
    return Wind = (function(_super) {
      __extends(Wind, _super);

      function Wind(x, y) {
        this.x = x;
        this.y = y;
        this.name = config.wind.name;
        this.img = config.wind.img;
        this.price = config.wind.price;
        this.attack = config.wind.attack;
        this.range = config.wind.range;
        this.speed = config.wind.speed;
        this.lastShot = 0;
        this.shots = [];
      }

      return Wind;

    })(Tower);
  });

}).call(this);

//# sourceMappingURL=wind.map
